import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Cairo } from "next/font/google";
import {Almarai} from "next/font/google";
import { Montserrat } from "next/font/google";
import AnimationProvider from "../components/provider/animation-provider";
import StoreProvider from '../components/provider/store-provider'
import Script from "next/script";
import { Suspense } from "react";
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';

const inter = Inter({
  subsets: ['latin'], // you can specify ['latin', 'cyrillic', etc.]
  display: 'swap',    // optional, but good for performance
  weight: ['400', '700'], // optional: pick weights you want
});

const almarai = Almarai({
  subsets: ['arabic'], // or ['latin', 'arabic'] if you want both
  weight: ['300', '400', '700', '800'], // available weights: 300–800
  display: 'swap',
})

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-cairo",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-montserrat",
});

const metadata: Metadata = {
  title: "Tayraan",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}) {

    // Ensure that the incoming `locale` is valid
    const {locale} = await params;
    if (!hasLocale(routing.locales, locale)) {
      notFound();
    }

    function getDirection(locale: string): 'rtl' | 'ltr' {
      return locale === 'ar' ? 'rtl' : 'ltr';
    }

    const dir = getDirection(locale);

  return (
    <html
      lang={locale}
      dir={dir}
      className={`${cairo.variable} ${montserrat.variable} ${almarai.className}`}
    >
      <Script src="/langs/lang-config.js" strategy="beforeInteractive" />
      <Script src="/langs/translation.js" strategy="beforeInteractive" />
      <Script src="//translate.google.com/translate_a/element.js?cb=TranslateInit" strategy="afterInteractive" />

      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin={"anonymous"}
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;500;600;700;800;900&family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Suspense>
          <StoreProvider>
          <AnimationProvider>

            {/* <GoogleTranslate /> */}
            <NextIntlClientProvider>{children}</NextIntlClientProvider>
            </AnimationProvider>
          </StoreProvider>
        </Suspense> 
      </body>
    </html>
  );
}
